baseURL = "https://rajkumargosavi.github.io/"
languageCode = "en-us"
title = "Dev Journal"
theme = "ananke"
enableRobotsTXT = true
SectionPagesMenu = "main"
recent_posts_number = 3

[pagination]
  pagerSize = 3


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2
  
  [[menu.main]]
    identifier = "practice"
    name = "Practice"
    url = "/"
    weight = 3

  [[menu.main]]
    identifier = "readings"
    name = "Readings"
    url = "/readings"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]